branch-defaults:
  master:
    environment: voyager
global:
  application_name: voyager
  default_ec2_keyname: voyager
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
